# Configuration file for AutoML Platform

# 📌 Data preprocessing settings
preprocessing:
  train_split: 0.8 # 80% training data
  scale_features: true # Standard scaling of features
  encode_categorical: true # Encode categorical features

# 📌 Hyperparameter tuning ranges
tuning:
  xgboost:
    bayesian:
      learning_rate: [0.01, 0.1]
      max_depth: [3, 5]
      n_iter: 10
    grid_search:
      learning_rate: [0.01, 0.1]
      max_depth: [3, 5]
    optuna:
      learning_rate: [0.01, 0.1]
      max_depth: [3, 5]

  svm:
    grid_search:
      C: [0.1, 1.0, 10]
      kernel: ["rbf", "linear"]
    optuna:
      C: [0.1, 10]
      kernel: ["rbf", "linear"]
    bayesian:
      C: [0.1, 10]
      n_iter: 10

  dnn:
    grid_search:
      units: [32, 64]
      layers: [1, 2]
    optuna:
      units: [32, 128]
      layers: [1, 3]
    bayesian:
      units: [32, 128]
      layers: [1, 3]
      n_iter: 10
